pub mod repr {

    use std::mem::ManuallyDrop;

    #[repr(C)]
    pub struct OneOf<
        One = (),
        Two = (),
        Three = (),
        Four = (),
        Five = (),
        Six = (),
        Seven = (),
        Eight = (),
        Nine = (),
        Ten = (),
        Eleven = (),
        Twelve = (),
        Thirteen = (),
        Fourteen = (),
        Fifteen = (),
        Sixteen = (),
        Seventeen = (),
        Eightteen = (),
        Nineteen = (),
        Twenty = (),
        TwentyOne = (),
        TwentyTwo = (),
        TwentyThree = (),
        TwentyFour = (),
        TwentyFive = (),
        TwentySix = (),
        TwentySeven = (),
        TwentyEight = (),
        TwentyNine = (),
        Thirty = (),
        ThirtyOne = (),
        ThirtyTwo = (),
        ThirtyThree = (),
        ThirtyFour = (),
        ThirtyFive = (),
        ThirtySix = (),
        ThirtySeven = (),
        ThirtyEight = (),
        ThirtyNine = (),
        Fourty = (),
        FourtyOne = (),
        FourtyTwo = (),
        FourtyThree = (),
        FourtyFour = (),
        FourtyFive = (),
        FourtySix = (),
        FourtySeven = (),
        FourtyEight = (),
        FourtyNine = (),
        Fifty = (),
    > {
        tag: std::ffi::c_uint,
        union: OneOfInt<
            One,
            Two,
            Three,
            Four,
            Five,
            Six,
            Seven,
            Eight,
            Nine,
            Ten,
            Eleven,
            Twelve,
            Thirteen,
            Fourteen,
            Fifteen,
            Sixteen,
            Seventeen,
            Eightteen,
            Nineteen,
            Twenty,
            TwentyOne,
            TwentyTwo,
            TwentyThree,
            TwentyFour,
            TwentyFive,
            TwentySix,
            TwentySeven,
            TwentyEight,
            TwentyNine,
            Thirty,
            ThirtyOne,
            ThirtyTwo,
            ThirtyThree,
            ThirtyFour,
            ThirtyFive,
            ThirtySix,
            ThirtySeven,
            ThirtyEight,
            ThirtyNine,
            Fourty,
            FourtyOne,
            FourtyTwo,
            FourtyThree,
            FourtyFour,
            FourtyFive,
            FourtySix,
            FourtySeven,
            FourtyEight,
            FourtyNine,
            Fifty,
        >,
    }

    impl<
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Ten,
        Eleven,
        Twelve,
        Thirteen,
        Fourteen,
        Fifteen,
        Sixteen,
        Seventeen,
        Eightteen,
        Nineteen,
        Twenty,
        TwentyOne,
        TwentyTwo,
        TwentyThree,
        TwentyFour,
        TwentyFive,
        TwentySix,
        TwentySeven,
        TwentyEight,
        TwentyNine,
        Thirty,
        ThirtyOne,
        ThirtyTwo,
        ThirtyThree,
        ThirtyFour,
        ThirtyFive,
        ThirtySix,
        ThirtySeven,
        ThirtyEight,
        ThirtyNine,
        Fourty,
        FourtyOne,
        FourtyTwo,
        FourtyThree,
        FourtyFour,
        FourtyFive,
        FourtySix,
        FourtySeven,
        FourtyEight,
        FourtyNine,
        Fifty,
    >
        OneOf<
            One,
            Two,
            Three,
            Four,
            Five,
            Six,
            Seven,
            Eight,
            Nine,
            Ten,
            Eleven,
            Twelve,
            Thirteen,
            Fourteen,
            Fifteen,
            Sixteen,
            Seventeen,
            Eightteen,
            Nineteen,
            Twenty,
            TwentyOne,
            TwentyTwo,
            TwentyThree,
            TwentyFour,
            TwentyFive,
            TwentySix,
            TwentySeven,
            TwentyEight,
            TwentyNine,
            Thirty,
            ThirtyOne,
            ThirtyTwo,
            ThirtyThree,
            ThirtyFour,
            ThirtyFive,
            ThirtySix,
            ThirtySeven,
            ThirtyEight,
            ThirtyNine,
            Fourty,
            FourtyOne,
            FourtyTwo,
            FourtyThree,
            FourtyFour,
            FourtyFive,
            FourtySix,
            FourtySeven,
            FourtyEight,
            FourtyNine,
            Fifty,
        >
    {
        pub fn tag(&self) -> std::ffi::c_uint {
            return self.tag;
        }

        // TODO FIXME REPLACE:
        pub unsafe fn get(&self) -> &One {
            return unsafe { &self.union.one };
        }
    }

    // TODO: Replace generics with typenum peano integer magic
    #[repr(C, align(8))]
    union OneOfInt<
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Ten,
        Eleven,
        Twelve,
        Thirteen,
        Fourteen,
        Fifteen,
        Sixteen,
        Seventeen,
        Eightteen,
        Nineteen,
        Twenty,
        TwentyOne,
        TwentyTwo,
        TwentyThree,
        TwentyFour,
        TwentyFive,
        TwentySix,
        TwentySeven,
        TwentyEight,
        TwentyNine,
        Thirty,
        ThirtyOne,
        ThirtyTwo,
        ThirtyThree,
        ThirtyFour,
        ThirtyFive,
        ThirtySix,
        ThirtySeven,
        ThirtyEight,
        ThirtyNine,
        Fourty,
        FourtyOne,
        FourtyTwo,
        FourtyThree,
        FourtyFour,
        FourtyFive,
        FourtySix,
        FourtySeven,
        FourtyEight,
        FourtyNine,
        Fifty,
    > {
        one: ManuallyDrop<One>,
        two: ManuallyDrop<Two>,
        three: ManuallyDrop<Three>,
        four: ManuallyDrop<Four>,
        five: ManuallyDrop<Five>,
        six: ManuallyDrop<Six>,
        seven: ManuallyDrop<Seven>,
        eight: ManuallyDrop<Eight>,
        nine: ManuallyDrop<Nine>,
        ten: ManuallyDrop<Ten>,
        eleven: ManuallyDrop<Eleven>,
        twelve: ManuallyDrop<Twelve>,
        thirteen: ManuallyDrop<Thirteen>,
        fourteen: ManuallyDrop<Fourteen>,
        fifteen: ManuallyDrop<Fifteen>,
        sixteen: ManuallyDrop<Sixteen>,
        seventeen: ManuallyDrop<Seventeen>,
        eightteen: ManuallyDrop<Eightteen>,
        nineteen: ManuallyDrop<Nineteen>,
        twenty: ManuallyDrop<Twenty>,
        twentyone: ManuallyDrop<TwentyOne>,
        twentytwo: ManuallyDrop<TwentyTwo>,
        twentythree: ManuallyDrop<TwentyThree>,
        twentyfour: ManuallyDrop<TwentyFour>,
        twentyfive: ManuallyDrop<TwentyFive>,
        twentysix: ManuallyDrop<TwentySix>,
        twentyseven: ManuallyDrop<TwentySeven>,
        twentyeight: ManuallyDrop<TwentyEight>,
        twentynine: ManuallyDrop<TwentyNine>,
        thirty: ManuallyDrop<Thirty>,
        thirtyone: ManuallyDrop<ThirtyOne>,
        thirtytwo: ManuallyDrop<ThirtyTwo>,
        thirtythree: ManuallyDrop<ThirtyThree>,
        thirtyfour: ManuallyDrop<ThirtyFour>,
        thirtyfive: ManuallyDrop<ThirtyFive>,
        thirtysix: ManuallyDrop<ThirtySix>,
        thirtyseven: ManuallyDrop<ThirtySeven>,
        thirtyeight: ManuallyDrop<ThirtyEight>,
        thirtynine: ManuallyDrop<ThirtyNine>,
        fourty: ManuallyDrop<Fourty>,
        fourtyone: ManuallyDrop<FourtyOne>,
        fourtytwo: ManuallyDrop<FourtyTwo>,
        fourtythree: ManuallyDrop<FourtyThree>,
        fourtyfour: ManuallyDrop<FourtyFour>,
        fourtyfive: ManuallyDrop<FourtyFive>,
        fourtysix: ManuallyDrop<FourtySix>,
        fourtyseven: ManuallyDrop<FourtySeven>,
        fourtyeight: ManuallyDrop<FourtyEight>,
        fourtynine: ManuallyDrop<FourtyNine>,
        fifty: ManuallyDrop<Fifty>,
    }
}
